#!/bin/bash

## Este script corre un ejemplo para bajar, instalar y usar Blast desde Biocontainers

# Ingresar al directorio de trabajo

cd /home/delil/Escritorio/Ej_blast

# Baja e instala BLAST

docker pull biocontainers/blast

# Desglosa el menú de ayuda de BLAST

docker run biocontainers/blast blastp -help

## Descarga las secuencias de interes

# Descarga la secuencia de un prion humano de UniProt

wget http://www.uniprot.org/uniprot/P04156.fasta

# Descarga la base de datos de proteínas del pez cebra

curl -O ftp://ftp.ncbi.nih.gov/refseq/D_rerio/mRNA_Prot/zebrafish.1.protein.faa.gz

# Descomprime el gzip

gunzip zebrafish.1.protein.faa.gz

# Monta el volumen y prepara la base de datos del pez cebra

docker run -v /home/delil/Escritorio/Ej_blast:/data/ biocontainers/blast makeblastdb -in zebrafish.1.protein.faa -dbtype prot

# Monta el volumen y realiza un blast de las secuencias de priones con la base de datos del pez cebra. 
docker run -v /home/delil/Escritorio/Ej_blast:/data/ biocontainers/blast blastp -query P04156.fasta -db zebrafish.1.protein.faa -out results.txt








